export const products = [
  {
    slug: 'moringa-powder',
    name: 'Moringa Powder',
    tagline: 'Nature\'s Multivitamin from India',
    short: 'Premium-grade, shade-dried Moringa Oleifera leaf powder rich in vitamins, minerals and antioxidants - sustainably sourced from Indian farms.',
    image: 'https://images.unsplash.com/photo-1704079698754-5e621edb610b?crop=entropy&cs=srgb&fm=jpg&q=85',
    gallery: [
      'https://images.unsplash.com/photo-1704079698754-5e621edb610b?crop=entropy&cs=srgb&fm=jpg&q=85',
      'https://images.pexels.com/photos/37911594/pexels-photo-37911594.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      'https://images.pexels.com/photos/34299/herbs-flavoring-seasoning-cooking.jpg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    ],
    color: 'from-emerald-500 to-green-600',
    description: 'Our Moringa Powder is produced from the finest Moringa Oleifera leaves cultivated in southern India. Carefully hand-harvested, shade-dried at controlled temperatures to preserve nutrients, and finely milled to deliver a vibrant green superfood powder ready for global wellness and food industries.',
    benefits: ['Rich in 90+ essential nutrients & antioxidants','High in plant-based protein, calcium, and iron','Supports immunity, energy and metabolism','Natural anti-inflammatory & detoxifying properties','100% pure - no fillers, additives or preservatives'],
    packaging: ['25 kg / 50 lb multi-wall kraft bags with PE liner','Customizable retail packaging from 100g–1kg','Private-label & white-label OEM available','Export pallets shrink-wrapped with desiccants'],
    availability: 'Year-round, 50–100 MT/month',
    specs: { 'Botanical Name': 'Moringa Oleifera', 'Mesh Size': '80–100 mesh', 'Color': 'Vibrant Green', 'Shelf Life': '24 months', 'Certifications': 'ISO, HACCP, USDA Organic, EU Organic' },
  },
  {
    slug: 'turmeric-powder',
    name: 'Turmeric Powder',
    tagline: 'The Golden Spice of India',
    short: 'High-curcumin Indian turmeric, finely milled and lab-tested - the gold standard for global culinary, nutraceutical and pharmaceutical markets.',
    image: 'https://images.pexels.com/photos/7988009/pexels-photo-7988009.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    gallery: [
      'https://images.pexels.com/photos/7988009/pexels-photo-7988009.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      'https://images.pexels.com/photos/7956502/pexels-photo-7956502.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      'https://images.pexels.com/photos/34299/herbs-flavoring-seasoning-cooking.jpg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    ],
    color: 'from-amber-500 to-orange-600',
    description: 'Sourced from the renowned turmeric belts of Erode, Sangli and Nizamabad, our Turmeric Powder boasts a naturally high curcumin content of 3–5%. Steam-sterilized, lab-tested, and ground to consistent fineness for export to spice, beverage, supplement and pharmaceutical buyers worldwide.',
    benefits: ['Naturally high curcumin (3–5%)','Steam-sterilized for global food safety','Vibrant golden color & authentic Indian aroma','Lab-tested for purity, heavy metals & pesticides','Versatile for culinary & nutraceutical use'],
    packaging: ['25 kg / 50 lb laminated PP bags','Retail jars & sachets 50g–500g','Bulk FCL & LCL shipments worldwide','Custom private-label packaging available'],
    availability: 'Year-round, 100–200 MT/month',
    specs: { 'Botanical Name': 'Curcuma Longa', 'Curcumin Content': '3–5%', 'Mesh Size': '60–80 mesh', 'Moisture': '< 8%', 'Certifications': 'FSSAI, ISO 22000, HACCP, USDA Organic' },
  },
  {
    slug: 'agricultural-products',
    name: 'Agricultural Products',
    tagline: 'Premium Commodities from Indian Farms',
    short: 'A diversified portfolio of pulses, grains, oilseeds and natural commodities - sourced directly from trusted Indian farmer networks.',
    image: 'https://images.pexels.com/photos/20841297/pexels-photo-20841297.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    gallery: [
      'https://images.pexels.com/photos/20841297/pexels-photo-20841297.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      'https://images.pexels.com/photos/36666146/pexels-photo-36666146.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      'https://images.unsplash.com/photo-1529313780224-1a12b68bed16?crop=entropy&cs=srgb&fm=jpg&q=85',
    ],
    color: 'from-blue-500 to-cyan-600',
    description: 'Globeon Exim offers a wide range of agricultural commodities including pulses, grains, oilseeds, spices and herbal products. By working directly with Indian farmer producer organizations (FPOs), we ensure traceability, fair pricing and consistent quality at scale for our global partners.',
    benefits: ['Direct-from-farm traceability','Strict QC at every batch','Wide product portfolio under one supplier','Competitive FOB & CIF pricing','Reliable global logistics network'],
    packaging: ['Jute bags, PP woven bags, BOPP bags','Custom branded packaging','Bulk container loading (FCL/LCL)','Phyto-sanitary certified shipments'],
    availability: 'Season-based, MOQ 5 MT',
    specs: { 'Category': 'Pulses, Grains, Oilseeds, Spices', 'Origin': 'India', 'Quality Grade': 'Export A-Grade', 'MOQ': '5 MT', 'Certifications': 'APEDA, Spices Board, FSSAI' },
  },
];

export const getProduct = (slug) => products.find(p => p.slug === slug);
